openapi: 3.0.3
info:
  title: disposable-email-project
  description: 'Disposable Email Project API'
  version: 0.0.1
servers:
  - url: /
    description: ''
paths:
  /accounts:
    post:
      operationId: postAccountCollection
      tags:
        - Account
      responses:
        '201':
          description: Account resource created
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Account.jsonld-account.read'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/xml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/xml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/csv:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/html:
              schema:
                $ref: '#/components/schemas/Account-account.read'
          links:
            GetAccountItem:
              operationId: getAccountItem
              parameters:
                id: $response.body#/id
              description: The `id` value returned in the response can be used as the `id` parameter in `GET /accounts/{id}`.
        '400':
          description: Invalid input
        '422':
          description: Unprocessable entity
      summary: Creates a Account resource.
      description: Creates a Account resource.
      parameters: []
      requestBody:
        description: The new Account resource
        content:
          application/ld+json:
            schema:
              $ref: '#/components/schemas/Account.jsonld-account.write'
          application/hal+json:
            schema:
              $ref: '#/components/schemas/Account-account.write'
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Account-account.write'
          application/json:
            schema:
              $ref: '#/components/schemas/Account-account.write'
          application/xml:
            schema:
              $ref: '#/components/schemas/Account-account.write'
          text/xml:
            schema:
              $ref: '#/components/schemas/Account-account.write'
          application/x-yaml:
            schema:
              $ref: '#/components/schemas/Account-account.write'
          text/csv:
            schema:
              $ref: '#/components/schemas/Account-account.write'
          text/html:
            schema:
              $ref: '#/components/schemas/Account-account.write'
        required: true
      deprecated: false
    parameters: []
  /accounts/{id}:
    get:
      operationId: getAccountItem
      tags:
        - Account
      responses:
        '200':
          description: Account resource
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Account.jsonld-account.read'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/xml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/xml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/csv:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/html:
              schema:
                $ref: '#/components/schemas/Account-account.read'
        '404':
          description: Resource not found
      summary: Retrieves a Account resource.
      description: Retrieves a Account resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    delete:
      operationId: deleteAccountItem
      tags:
        - Account
      responses:
        '204':
          description: Account resource deleted
        '404':
          description: Resource not found
      summary: Removes the Account resource.
      description: Removes the Account resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /domains:
    get:
      operationId: getDomainCollection
      tags:
        - Domain
      responses:
        '200':
          description: Domain collection
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  hydra:member:
                    type: array
                    items:
                      $ref: '#/components/schemas/Domain.jsonld'
                  hydra:totalItems:
                    type: integer
                    minimum: 0
                  hydra:view:
                    type: object
                    properties:
                      '@id':
                        type: string
                        format: iri-reference
                      '@type':
                        type: string
                      hydra:first:
                        type: string
                        format: iri-reference
                      hydra:last:
                        type: string
                        format: iri-reference
                      hydra:previous:
                        type: string
                        format: iri-reference
                      hydra:next:
                        type: string
                        format: iri-reference
                  hydra:search:
                    type: object
                    properties:
                      '@type':
                        type: string
                      hydra:template:
                        type: string
                      hydra:variableRepresentation:
                        type: string
                      hydra:mapping:
                        type: array
                        items:
                          type: object
                          properties:
                            '@type':
                              type: string
                            variable:
                              type: string
                            property:
                              type: string
                              nullable: true
                            required:
                              type: boolean
                required:
                  - hydra:member
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
            application/vnd.api+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
            application/x-yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
            text/csv:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Domain'
      summary: Retrieves the collection of Domain resources.
      description: Retrieves the collection of Domain resources.
      parameters:
        - name: page
          in: query
          description: The collection page number
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
          style: form
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /domains/{id}:
    get:
      operationId: getDomainItem
      tags:
        - Domain
      responses:
        '200':
          description: Domain resource
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Domain.jsonld'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Domain'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Domain'
            application/json:
              schema:
                $ref: '#/components/schemas/Domain'
            application/xml:
              schema:
                $ref: '#/components/schemas/Domain'
            text/xml:
              schema:
                $ref: '#/components/schemas/Domain'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Domain'
            text/csv:
              schema:
                $ref: '#/components/schemas/Domain'
            text/html:
              schema:
                $ref: '#/components/schemas/Domain'
        '404':
          description: Resource not found
      summary: Retrieves a Domain resource.
      description: Retrieves a Domain resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /me:
    get:
      operationId: get_meAccountItem
      tags:
        - Account
      responses:
        '200':
          description: Account resource
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Account.jsonld-account.read'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/json:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/xml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/xml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/csv:
              schema:
                $ref: '#/components/schemas/Account-account.read'
            text/html:
              schema:
                $ref: '#/components/schemas/Account-account.read'
        '404':
          description: Resource not found
      summary: Retrieves a Account resource.
      description: Retrieves a Account resource.
      parameters: []
      deprecated: false
    parameters: []
  /messages:
    get:
      operationId: getMessageCollection
      tags:
        - Message
      responses:
        '200':
          description: Message collection
          content:
            application/ld+json:
              schema:
                type: object
                properties:
                  hydra:member:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message.jsonld-messages.read'
                  hydra:totalItems:
                    type: integer
                    minimum: 0
                  hydra:view:
                    type: object
                    properties:
                      '@id':
                        type: string
                        format: iri-reference
                      '@type':
                        type: string
                      hydra:first:
                        type: string
                        format: iri-reference
                      hydra:last:
                        type: string
                        format: iri-reference
                      hydra:previous:
                        type: string
                        format: iri-reference
                      hydra:next:
                        type: string
                        format: iri-reference
                  hydra:search:
                    type: object
                    properties:
                      '@type':
                        type: string
                      hydra:template:
                        type: string
                      hydra:variableRepresentation:
                        type: string
                      hydra:mapping:
                        type: array
                        items:
                          type: object
                          properties:
                            '@type':
                              type: string
                            variable:
                              type: string
                            property:
                              type: string
                              nullable: true
                            required:
                              type: boolean
                required:
                  - hydra:member
            application/hal+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
            application/vnd.api+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
            text/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
            application/x-yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
            text/csv:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
            text/html:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Message-messages.read'
      summary: Retrieves the collection of Message resources.
      description: Retrieves the collection of Message resources.
      parameters:
        - name: page
          in: query
          description: The collection page number
          required: false
          deprecated: false
          allowEmptyValue: true
          schema:
            type: integer
            default: 1
          style: form
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /messages/{id}:
    get:
      operationId: getMessageItem
      tags:
        - Message
      responses:
        '200':
          description: Message resource
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Message.jsonld-message.read'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Message-message.read'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Message-message.read'
            application/json:
              schema:
                $ref: '#/components/schemas/Message-message.read'
            application/xml:
              schema:
                $ref: '#/components/schemas/Message-message.read'
            text/xml:
              schema:
                $ref: '#/components/schemas/Message-message.read'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Message-message.read'
            text/csv:
              schema:
                $ref: '#/components/schemas/Message-message.read'
            text/html:
              schema:
                $ref: '#/components/schemas/Message-message.read'
        '404':
          description: Resource not found
      summary: Retrieves a Message resource.
      description: Retrieves a Message resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    delete:
      operationId: deleteMessageItem
      tags:
        - Message
      responses:
        '204':
          description: Message resource deleted
        '404':
          description: Resource not found
      summary: Removes the Message resource.
      description: Removes the Message resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    patch:
      operationId: patchMessageItem
      tags:
        - Message
      responses:
        '200':
          description: Message resource updated
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Message.jsonld-message.write'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Message-message.write'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Message-message.write'
            application/json:
              schema:
                $ref: '#/components/schemas/Message-message.write'
            application/xml:
              schema:
                $ref: '#/components/schemas/Message-message.write'
            text/xml:
              schema:
                $ref: '#/components/schemas/Message-message.write'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Message-message.write'
            text/csv:
              schema:
                $ref: '#/components/schemas/Message-message.write'
            text/html:
              schema:
                $ref: '#/components/schemas/Message-message.write'
          links:
            GetMessageItem:
              operationId: getMessageItem
              parameters:
                id: $response.body#/id
              description: The `id` value returned in the response can be used as the `id` parameter in `GET /messages/{id}`.
        '400':
          description: Invalid input
        '404':
          description: Resource not found
        '422':
          description: Unprocessable entity
      summary: Updates the Message resource.
      description: Updates the Message resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      requestBody:
        description: The updated Message resource
        content:
          application/merge-patch+json:
            schema:
              $ref: '#/components/schemas/Message-message.write'
          application/ld+json:
            schema:
              $ref: '#/components/schemas/Message-message.write'
          application/vnd.api+json:
            schema:
              $ref: '#/components/schemas/Message-message.write'
        required: true
      deprecated: false
    parameters: []
  /sources/{id}:
    get:
      operationId: getSourceItem
      tags:
        - Source
      responses:
        '200':
          description: Source resource
          content:
            application/ld+json:
              schema:
                $ref: '#/components/schemas/Source.jsonld-source.read'
            application/hal+json:
              schema:
                $ref: '#/components/schemas/Source-source.read'
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Source-source.read'
            application/json:
              schema:
                $ref: '#/components/schemas/Source-source.read'
            application/xml:
              schema:
                $ref: '#/components/schemas/Source-source.read'
            text/xml:
              schema:
                $ref: '#/components/schemas/Source-source.read'
            application/x-yaml:
              schema:
                $ref: '#/components/schemas/Source-source.read'
            text/csv:
              schema:
                $ref: '#/components/schemas/Source-source.read'
            text/html:
              schema:
                $ref: '#/components/schemas/Source-source.read'
        '404':
          description: Resource not found
      summary: Retrieves a Source resource.
      description: Retrieves a Source resource.
      parameters:
        - name: id
          in: path
          description: Resource identifier
          required: true
          deprecated: false
          allowEmptyValue: false
          schema:
            type: string
          style: simple
          explode: false
          allowReserved: false
      deprecated: false
    parameters: []
  /token:
    post:
      operationId: postCredentialsItem
      tags:
        - Token
      responses:
        '200':
          description: Get JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
      summary: Get JWT token to login.
      description: ''
      parameters: []
      requestBody:
        description: Generate new JWT Token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
        required: false
      deprecated: false
    parameters: []
components:
  schemas:
    Account-account.read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        address:
          format: email
          externalDocs:
            url: https://schema.org/email
          type: string
        quota:
          type: integer
        used:
          type: integer
        isDisabled:
          type: boolean
        isDeleted:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - address
    Account-account.write:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        address:
          format: email
          externalDocs:
            url: https://schema.org/email
          type: string
        password:
          type: string
      required:
        - address
        - password
    Account.jsonld-account.read:
      type: object
      description: ''
      properties:
        '@context':
          readOnly: true
          oneOf:
            - type: string
            - type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum:
                    - http://www.w3.org/ns/hydra/core#
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
        address:
          format: email
          externalDocs:
            url: https://schema.org/email
          type: string
        quota:
          type: integer
        used:
          type: integer
        isDisabled:
          type: boolean
        isDeleted:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - address
    Account.jsonld-account.write:
      type: object
      description: ''
      properties:
        '@context':
          readOnly: true
          oneOf:
            - type: string
            - type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum:
                    - http://www.w3.org/ns/hydra/core#
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
        address:
          format: email
          externalDocs:
            url: https://schema.org/email
          type: string
        password:
          type: string
      required:
        - address
        - password
    Domain:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        domain:
          type: string
        isActive:
          type: boolean
        isPrivate:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Domain.jsonld:
      type: object
      description: ''
      properties:
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        '@context':
          readOnly: true
          oneOf:
            - type: string
            - type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum:
                    - http://www.w3.org/ns/hydra/core#
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        id:
          readOnly: true
          type: string
        domain:
          type: string
        isActive:
          type: boolean
        isPrivate:
          type: boolean
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    Message-message.read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        accountId:
          readOnly: true
          type: string
          format: iri-reference
        msgid:
          readOnly: true
          type: string
        from:
          example:
            address: from@example.com
            name: John Doe
          readOnly: true
          externalDocs:
            url: https://schema.org/sender
          type: array
          items:
            type: string
          nullable: true
        to:
          type: array
          items:
            type: array
            items:
              example:
                - address: receiver@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/recipient
              nullable: true
        cc:
          type: array
          items:
            type: array
            items:
              example:
                - address: cc@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/ccRecipient
              nullable: true
        bcc:
          type: array
          items:
            type: array
            items:
              example:
                - address: bcc@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/bccRecipient
              nullable: true
        subject:
          readOnly: true
          externalDocs:
            url: https://schema.org/about
          type: string
        seen:
          type: boolean
        flagged:
          readOnly: true
          type: boolean
        isDeleted:
          type: boolean
        verifications:
          readOnly: true
          type: array
          items:
            type: string
        retention:
          type: boolean
        retentionDate:
          type: string
          format: date-time
        text:
          readOnly: true
          type: string
        html:
          readOnly: true
          type: array
          items:
            type: string
        hasAttachments:
          readOnly: true
          type: boolean
        attachments:
          type: array
          items:
            type: array
            items:
              example:
                - id: ATTACH000001
                  filename: happy.png
                  contentType: image/png
                  disposition: attachment
                  transferEncoding: base64
                  related: false
                  size: 666
                  downloadUrl: /messages/id/attachment/ATTACH000001
          externalDocs:
            url: https://schema.org/messageAttachment
        size:
          readOnly: true
          externalDocs:
            url: https://schema.org/fileSize
          type: integer
        downloadUrl:
          readOnly: true
          externalDocs:
            url: http://schema.org/contentUrl
          type: string
        createdAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateSent
          type: string
          format: date-time
        updatedAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateReceived
          type: string
          format: date-time
    Message-message.write:
      type: object
      description: ''
      properties:
        seen:
          type: boolean
    Message-messages.read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        accountId:
          readOnly: true
          type: string
          format: iri-reference
        msgid:
          readOnly: true
          type: string
        from:
          example:
            address: from@example.com
            name: John Doe
          readOnly: true
          externalDocs:
            url: https://schema.org/sender
          type: array
          items:
            type: string
          nullable: true
        to:
          type: array
          items:
            type: array
            items:
              example:
                - address: receiver@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/recipient
              nullable: true
        subject:
          readOnly: true
          externalDocs:
            url: https://schema.org/about
          type: string
        intro:
          readOnly: true
          externalDocs:
            url: https://schema.org/backstory
          type: string
        seen:
          type: boolean
        isDeleted:
          type: boolean
        hasAttachments:
          readOnly: true
          type: boolean
        size:
          readOnly: true
          externalDocs:
            url: https://schema.org/fileSize
          type: integer
        downloadUrl:
          readOnly: true
          externalDocs:
            url: http://schema.org/contentUrl
          type: string
        createdAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateSent
          type: string
          format: date-time
        updatedAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateReceived
          type: string
          format: date-time
    Message.jsonld-message.read:
      type: object
      description: ''
      properties:
        '@context':
          readOnly: true
          oneOf:
            - type: string
            - type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum:
                    - http://www.w3.org/ns/hydra/core#
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
        accountId:
          readOnly: true
          type: string
          format: iri-reference
        msgid:
          readOnly: true
          type: string
        from:
          example:
            address: from@example.com
            name: John Doe
          readOnly: true
          externalDocs:
            url: https://schema.org/sender
          type: array
          items:
            type: string
          nullable: true
        to:
          type: array
          items:
            type: array
            items:
              example:
                - address: receiver@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/recipient
              nullable: true
        cc:
          type: array
          items:
            type: array
            items:
              example:
                - address: cc@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/ccRecipient
              nullable: true
        bcc:
          type: array
          items:
            type: array
            items:
              example:
                - address: bcc@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/bccRecipient
              nullable: true
        subject:
          readOnly: true
          externalDocs:
            url: https://schema.org/about
          type: string
        seen:
          type: boolean
        flagged:
          readOnly: true
          type: boolean
        isDeleted:
          type: boolean
        verifications:
          readOnly: true
          type: array
          items:
            type: string
        retention:
          type: boolean
        retentionDate:
          type: string
          format: date-time
        text:
          readOnly: true
          type: string
        html:
          readOnly: true
          type: array
          items:
            type: string
        hasAttachments:
          readOnly: true
          type: boolean
        attachments:
          type: array
          items:
            type: array
            items:
              example:
                - id: ATTACH000001
                  filename: happy.png
                  contentType: image/png
                  disposition: attachment
                  transferEncoding: base64
                  related: false
                  size: 666
                  downloadUrl: /messages/id/attachment/ATTACH000001
              externalDocs:
                url: https://schema.org/messageAttachment
        size:
          readOnly: true
          externalDocs:
            url: https://schema.org/fileSize
          type: integer
        downloadUrl:
          readOnly: true
          externalDocs:
            url: http://schema.org/contentUrl
          type: string
        createdAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateSent
          type: string
          format: date-time
        updatedAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateReceived
          type: string
          format: date-time
    Message.jsonld-message.write:
      type: object
      description: ''
      properties:
        '@context':
          readOnly: true
          oneOf:
            - type: string
            - type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum:
                    - http://www.w3.org/ns/hydra/core#
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        seen:
          type: boolean
    Message.jsonld-messages.read:
      type: object
      description: ''
      properties:
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        '@context':
          readOnly: true
          oneOf:
            - type: string
            - type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum:
                    - http://www.w3.org/ns/hydra/core#
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        id:
          readOnly: true
          type: string
        accountId:
          readOnly: true
          type: string
          format: iri-reference
        msgid:
          readOnly: true
          type: string
        from:
          example:
            address: from@example.com
            name: John Doe
          readOnly: true
          externalDocs:
            url: https://schema.org/sender
          type: array
          items:
            type: string
          nullable: true
        to:
          type: array
          items:
            type: array
            items:
              example:
                - address: receiver@example.com
                  name: John Doe
              readOnly: true
              externalDocs:
                url: https://schema.org/recipient
              nullable: true
        subject:
          readOnly: true
          externalDocs:
            url: https://schema.org/about
          type: string
        intro:
          readOnly: true
          externalDocs:
            url: https://schema.org/backstory
          type: string
        seen:
          type: boolean
        isDeleted:
          type: boolean
        hasAttachments:
          readOnly: true
          type: boolean
        size:
          readOnly: true
          externalDocs:
            url: https://schema.org/fileSize
          type: integer
        downloadUrl:
          readOnly: true
          externalDocs:
            url: http://schema.org/contentUrl
          type: string
        createdAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateSent
          type: string
          format: date-time
        updatedAt:
          readOnly: true
          externalDocs:
            url: https://schema.org/dateReceived
          type: string
          format: date-time
    Source-source.read:
      type: object
      description: ''
      properties:
        id:
          readOnly: true
          type: string
        downloadUrl:
          externalDocs:
            url: http://schema.org/contentUrl
          type: string
          nullable: true
        data:
          type: string
    Source.jsonld-source.read:
      type: object
      description: ''
      properties:
        '@context':
          readOnly: true
          oneOf:
            - type: string
            - type: object
              properties:
                '@vocab':
                  type: string
                hydra:
                  type: string
                  enum:
                    - http://www.w3.org/ns/hydra/core#
              required:
                - '@vocab'
                - hydra
              additionalProperties: true
        '@id':
          readOnly: true
          type: string
        '@type':
          readOnly: true
          type: string
        id:
          readOnly: true
          type: string
        downloadUrl:
          externalDocs:
            url: http://schema.org/contentUrl
          type: string
          nullable: true
        data:
          type: string
    Token:
      type: object
      properties:
        token:
          type: string
          readOnly: true
    Credentials:
      type: object
      properties:
        address:
          type: string
          example: test@example.com
        password:
          type: string
          example: password
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: Authorization